version: 2
jobs:
  build_node11:
    docker:
      - image: circleci/node:11

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-v11-{{ checksum "package.json" }}
            - v1-dependencies-v11-
            - v1-dependencies-

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v11-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      # - run:
      #     name: coverage reporting
      #     command: npm run coverage:submit

      - persist_to_workspace:
          root: ~/
          paths:
            - project/*

  build_node10:
    docker:
      - image: circleci/node:10

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-v10-{{ checksum "package.json" }}
            - v1-dependencies-v10-
            - v1-dependencies-

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v10-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      # - run:
      #     name: coverage reporting
      #     command: npm run coverage:submit

      - persist_to_workspace:
          root: ~/
          paths:
            - project/*

  build_node8:
    docker:
      - image: circleci/node:8

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-v8-{{ checksum "package.json" }}
            - v1-dependencies-v8-
            - v1-dependencies-

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v8-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:10

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: configure NPM registry
          command: echo "THIS WILL DEPLOY TO NPM eventually"

      # - run:
      #     name: configure NPM registry
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #
      # - run:
      #     name: configure GitHub SSH
      #     command: mkdir -p ~/.ssh && ssh-keyscan -H github.com > ~/.ssh/known_hosts
      #
      # - run:
      #     working_directory: ~/project
      #     name: publish
      #     command: |
      #       npm publish && npm run release:tag;
workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build_node11
      - build_node10
      - build_node8
      - deploy:
          requires:
            - build_node11
            - build_node10
            - build_node8
          filters:
            branches:
              only: master
